version: "3.8"
services:
  app:
    build: .
    container_name: my-accommodations-container
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: mysecret
      DB_NAME: myaccommodationsdb
      SLACK_WEBHOOK_URL: "https://hooks.slack.com/...somewebhook..."
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: my-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: mysecret
      MARIADB_DATABASE: myaccommodationsdb
    ports:
      - "3306:3306"
